### ISSUE TITLE
By doesn't work inside a for

### ISSUE THREAD

**Issue by pmargreff** [JuliaStats/DataFrames.jl#1043]
I'm trying use a by, but when I try it inside a for it doesn't work, when I try outside works fine

Example :
```
for col in eachcol(set)
    println("Hello") 
end
by(set, [:Temperature], nrow)
```

This one works fine, but when I try the next, the output isn't showed: -

```
  for col in eachcol(set)
    println("Hello") 
    by(set, [:Temperature], nrow)
  end

```

The output should be how the follow in both case, but only appear in first one:

```
3×2 DataFrames.DataFrame
│ Row │ Temperature │ x1 │
├─────┼─────────────┼────┤
│ 1   │ "Cool"      │ 4  │
│ 2   │ "Hot"       │ 4  │
│ 3   │ "Mild"      │ 6  │


```
It's a language bug or i'm get wrong something in the syntax?

**Comment by davidagold** [comment]
This is because `by` returns a `DataFrame`, and an object returned to the global scope in the REPL is automatically shown. When you include the `by` in the loop, it returns the `DataFrame` to the local scope of the loop; the loop does not return anything to the global scope of `Main` (the "REPL module"), hence nothing is shown in the REPL. If you just want to show each result of `by` inside the loop, you can do

```julia
  for col in eachcol(set)
    show(by(set, [:Temperature], nrow))
    println() # otherwise the shown DataFrames run together
  end
```

Or you can store each result in a `Vector` of `DataFrame`s for future manipulation:
```julia
result_dfs = Vector{DataFrame}()
for col in eachcol(set)
    res = by(set, [:Temperature], nrow)
    push!(result_dfs, res)
end
```

**Comment by pmargreff** [comment]
both worked, thanks man.
