### ISSUE TITLE
reference level of contrasts in ModelMatrix 

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/DataFrames.jl#1095]
I noticed that tests began failing on the master version of the [`GLM package`](https://github.com/JuliaStats/GLM.jl) and eventually tracked the problem to the default contrasts for a `CategoricalVector` not using the same ordering as the levels.  See [this example](https://github.com/dmbates/JSM/blob/master/Contrasts.ipynb).

In the example my GLM package repository is dirty because I had made some changes and was running the package tests before committing the changes.  That was when I saw this problem.

**Comment by kleinschmidt** [comment]
I think the problem is somewhere in copying the data frame into the `ModelFrame`.

```julia
julia> mf = ModelFrame(admit ~ 1 + gre + gpa + rankf, admit)
...
julia> levels(admit[:rankf])
4-element Array{Int64,1}:
 1
 2
 3
 4

julia> levels(mf.df[:rankf])
4-element Array{Int64,1}:
 3
 1
 4
 2
```

**Comment by kleinschmidt** [comment]
And in particular, in `null_omit` which indexes the original dataframe by row, returning one with complete cases only. This causes the categorical column to re-compute the levels, e.g.,

```julia
julia> admit[1:4, :rankf] |> levels
3-element Array{Int64,1}:
 3
 1
 4
```

**Comment by kleinschmidt** [comment]
What I think needs to happen here is twofold. First, we should use something like a `view` or `SubDataFrame` that won't trigger re-leveling. Second, we need to switch to using `unique` or something like that instead of `levels` (as discussed in #1081), but do so in a way that respects the ordering of the levels.

**Comment by nalimilan** [comment]
The `CategoricalArrays` constructors sort levels lexicographically when passed a standard array, and preserve ordering of levels when passed a `CategoricalArray`. The bug here is that `getindex` for `CategoricalArrays` doesn't preserve the order. This is just because I've relied on the generic `AbstractArray` method for now; I'll fix it. Using a view would probably also be a good idea for performance, but currently you can't call `levels` on a `CategoricalArray` view; not sure what's the best way to get this working.

I have some code locally for `unique`, will push it soon. Anyway, both `unique` and `levels` will use the same ordering: it's just that `unique` won't include levels that are not used.

**Comment by kleinschmidt** [comment]
For `view`/`levels`, how about something like

```julia
levels{T,N,P<:Union{CategoricalArray, NullableCategoricalArray},I,L}(sa::SubArray{T,N,P,I,L}) = levels(sa.parent)
```

**Comment by dmbates** [comment]
@nalimilan You probably know that the behavior in R is not to reevaluate the levels when using `getindex` but to have a separate function `droplevels` which drops unused levels, if there are any.  It should be very fast to determine the levels represented using `IntSet(var.refs)` which could be used in a `droplevels` function.

**Comment by nalimilan** [comment]
@dmbates Yes, that's the intended behaviour (and indeed `droplevels!` already exists). Determining the set of used levels can be even a bit faster than what you describe by short-circuiting if all levels have been found (I'll file a PR soon).

**Comment by dmbates** [comment]
Has this issue been fixed?  I have the master branch of CategoricalArrays and DataFrames but I am still getting scrambling of the levels in the coefficients.

**Comment by nalimilan** [comment]
Not yet. We have support for `view` for DataFrames doesn't use it, and I've yet to fix `getindex` in CategoricalArrays. Will do that soon.

**Comment by dmbates** [comment]
Thank you.

**Comment by nalimilan** [comment]
I've tested it, and https://github.com/nalimilan/CategoricalArrays.jl/pull/35 fixes the problem. Will close after tagging a new release.

**Comment by dmbates** [comment]
Thanks @nalimilan.  Very much appreciated.

**Comment by nalimilan** [comment]
Tagged as 0.1.0 (https://github.com/JuliaLang/METADATA.jl/pull/6792). Could be worth adding a test and bumping the required version, though.
