### ISSUE TITLE
Inconsistent behavior across initialization strategies

### ISSUE THREAD

**Issue by micahjsmith** [JuliaStats/DataFrames.jl#1127]
I'm not really sure how to phrase this issue but I'm getting some confusing behavior with different ways of initializing an empty DataFrame with a desired schema. Using the constructor that takes a vector of column data and a vector of column names, I get different behavior with the resulting DataFrame based on how I created an empty vector of column data even though the variables seem to be equal. 

```julia
using DataFrames

strings = ["a", "b", "c"]
fnames = [:f1, :f2, :f3]

col1 = repmat(Any[[]], 3)
col2 = Any[[],[],[]]

colequal = isequal(col1, col2)
println("Columns are equal: $(colequal)")

df1 = DataFrame(col1, fnames)
df2 = DataFrame(col2, fnames)

push!(df1, data(strings))
push!(df2, data(strings))

dfequal = isequal(df1, df2)
println("DataFrames are equal: $(dfequal)")
```

For me, this prints
```
Columns are equal: true
DataFrames are equal: false
```

I'm not sure what is going on or if this is expected behavior or not.

Note that for the first construction, the content of `df1` at the end of the script is the data replicated three times, column-wise, while for the second construction, the content of `df2` is a single row with the given data, as expected.

**Comment by tshort** [comment]
I can't reproduce your answers with Julia v0.5.0. `col1` and `col2` are different for me. Also, your columns in col1 are not typed. I don't know if that was intentional or not.

**Comment by micahjsmith** [comment]
Strange that you aren't able to reproduce this. I'm able to reproduce it on separate Windows, Linux, and macOS machines as well as on JuliaBox. All using DataFrames v0.8.5. One configuration:
```
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: unknown
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Prescott)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```

**Comment by nalimilan** [comment]
I was able to reproduce it, but that's not an issue with DataFrames: it's just due to how `repmat` works. `col1` is a vector holding three times the *same* empty vector. So when you change one of "them", all are affected. That means `push!` adds "a" to the first column, then "b" to the second column (which is the same), then "c" to the third column (which is again the same).

The docs for `repmat` and `repeat` could be improved to mention this pitfall.

BTW, working with `Vector{Any}` inside a `DataFrame` is not a good idea for performance, nor for clarity.
