### ISSUE TITLE
Rename dropna to complete_cases or vice-versa

### ISSUE THREAD

**Issue by juliohm** [JuliaStats/DataFrames.jl#1156]
The `dropna` method only works with DataArray whereas the `complete_cases` method only works with DataFrame. Could these be merged into a single name to make user's life easier?

I only found `complete_cases` because I asked on Discourse: https://discourse.julialang.org/t/is-there-a-dropna-for-dataframe/1777

**Comment by nalimilan** [comment]
I guess `complete_cases` was inspired by the R function with the same name. OTOH Pandas calls it [`dropna`](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.dropna.html). With the move to NullableArrays, our function should be `dropnull`, though.

One difference is that `complete_cases` returns a boolean vector, while `complete_cases!` drops rows with missing entries. If we rename it to `dropnull`, we will lose the first version. Maybe that's not an issue, though.

**Comment by piever** [comment]
Wouldn't it be more consistent to have `dropnull` return the subdataframe with only complete rows, `dropnull!` drop rows with missing entries (in place) and  `complete_cases` return the boolean vector? It seems counter-intuitive that `complete_cases` and `complete_cases!` do different things.

**Comment by nalimilan** [comment]
Yes, that's a possibility.

**Comment by juliohm** [comment]
So many names, I am not even following the discussion, we definitely need more consistent naming.

**Comment by cjprybol** [comment]
Linking this with https://github.com/JuliaStats/DataFrames.jl/issues/602 in the 0.9.0 milestone. @nalimilan suggested in that issue what @piever suggested here. `dropnull` is implemented [here in NullableArrays.jl](https://github.com/JuliaStats/NullableArrays.jl/blob/bdc46144724b1fdf891881acfacc2eaa87777abd/src/primitives.jl#L163), and could be imported and extended within this package. I did not see a `dropnull!` function implemented in NullableArrays, so that could be defined here or defined in NullableArrays and then extended here. With those changes, mark `complete_cases!` for deprecation and leave the current `complete_cases` as is. Does that sound right? Thoughts on where to first define `dropnull!`?

**Comment by nalimilan** [comment]
I had forgotten about that issue. Closing in favor of https://github.com/JuliaStats/DataFrames.jl/issues/602 then.

`dropnull!` should live in NullableArrays. It should be easy to implement using `deleteat!`.
