### ISSUE TITLE
memory-mapped DataFrame

### ISSUE THREAD

**Issue by HarlanH** [JuliaStats/DataFrames.jl#25]
There are several options here, from indexing CSV rows to allow random access to giant CSV files, to creating a new binary file format for storing DataVecs that supports mmap-style direct memory mapping.

**Comment by skanskan** [comment]
I agree, we need a platform able to work transparently with data of any size, at least bigger than memory, and ideally distributed on several computers.

Solutions such as Spark are not complete, they only offer the basic functionalities to build something else.

We don't just need to be able to get some summaries, as we do with databases,  we need to be able to do all operations with big data, operations such as multiplying to big matrixes, fitting a mixed-effect models, MCMC, etc.

Bigmemory or ff allows you to do some simple things but they cannot be used by other packages like lme4.

**Comment by quinnj** [comment]
I think this can be closed in light of the new [Feather.jl](https://github.com/JuliaStats/Feather.jl) package, which is essentially a a cross-language binary storage format for dataframes (R, pandas, etc.). It's fast and efficient because the files are mmapped directly and the each column is `unsafe_wrap(Array)` into NullableArrays=>DataFrame. Obviously, NullableArray support is not quite 100% with DataFrames, but should soon be.

**Comment by ViralBShah** [comment]
Closing. Can be reopened in the context of Feather.jl.
