### ISSUE TITLE
readtable doesn't try to promote Int32 on 32bit system.

### ISSUE THREAD

**Issue by adamczykm** [JuliaStats/DataFrames.jl#736]
As in title. I got a column with some big values - unix timestamps. The readtable function converts them to Int32, leaving me with negative values. It might be really troublesome when unnoticed. It doesn't even warn.

**Comment by davidanthoff** [comment]
We just ran into this issue: we read a CSV file that has one column that has some very large integer numbers in it, too large for an ``Int64``. The current behavior is really a bug, i.e. ``readtable`` just tries to read these into ``Int64``s, overflows and doesn't even warn about this.

I can see three alternative behaviors, and each one of these would be preferable:
1. Properly detect the type, if the numbers e.g. would fit into a ``Int128`` just use that as the type
2. Use ``String`` as the datatype. At least there is no data loss/corruption in that case
3. Give a warning. Not great, but at least it would alert people that there was a data corruption.

**Comment by johnmyleswhite** [comment]
I would vote for detecting overflow and promoting to `String`. Detecting overflow wouldn't be too hard to add here: https://github.com/JuliaStats/DataFrames.jl/blob/96790b2a152da070a4fcedb59e0276216c100048/src/dataframe/io.jl#L375

Making it fast might be hard though.

If CSV.jl does this better, we might want to not work on this and focus on switching everyone over to that.

**Comment by davidanthoff** [comment]
I looked at that code but can't really figure out how to implement this, I think one needs a bit more understanding of the code base to implement this.

I'm hesitant about the CSV.jl route for a couple of reasons: I think it would be way premature to stop fixing bugs in core functionality in DataFrames at this point, CSV seems in beta and quite complicated, whereas DataFrames is used by a lot of people, so it would be great if we could continue to fix issues there. Also, I looked at CSV.jl and it seems quite complicated... Certainly I couldn't find a function that is as simple as ``readtable`` there. But having something of the complexity level of ``readtable`` seems really crucial for DataFrames. So, long story short, I don't really see that CSV.jl is ready to replace reading from text files for DataFrames at this point.

**Comment by ViralBShah** [comment]
@quinnj

**Comment by quinnj** [comment]
CSV.jl is certainly ready for use, even reading DataFrames,
```julia
using DataFrames
using CSV

df = DataFrame(CSV.csv("my_csv_file.csv"; types=Dict(1=>Int128))
```
this example will read `my_csv_files.csv` in as a DataFrame, reading column 1 as an `Int128`. By default, Integer columns are read in as Int64 on all systems.

I'm curious what you find complicated about CSV.jl? The DataStreams interface can seem a little awkward at first, but the complete interop between CSV-SQLite-ODBC-DataFrames (and soon [Feather](https://blog.rstudio.org/2016/03/29/feather/)) seems well worth the implementation.

Do let me know if you run into any issues; happy to help evolve the API to be easier in any way.

**Comment by davidanthoff** [comment]
Having that simple code example be part of the README would go a *long* way making this easier to understand. I read through the existing CSV.jl and DataStreams.jl README files and was essentially completely lost. There are long lists of types and functions and concepts, but quite frankly if all I want to do is read a csv file into a DataFrame we can't seriously expect people to understand the the "workflow" of how to use this DataStreams.jl concept. I'm sure the whole setup makes a lot of sense for people that have more complicated requirements, but I don't think one can do away with a simple ``readtable`` like API for DataFrames that works.

So, maybe a good way forward would be this:
- Add helpful examples to CSV.jl's README on how to do common operations, instead of starting with a list of functions/types/concepts
- For DataFrames in particular, one could probably wrap the whole CSV/DataStreams loading code in convenience ``readtable`` like functions? Maybe even replace the existing ``readtable`` functions so that they use CSV.jl under the hood? Having a simple, permanent and robust ``readtable`` like interface seems really, really key. A more sophisticated DataStreams.jl based option as an alternative seems great, but for the occasional user it would really be a major barrier.

I do think there is a second question of automatic type detection. I think @johnmyleswhite suggestion that a reader should default to ``String`` if a value can't be read as an ``Int64`` makes a lot of sense, just losing data and being quite about it seems really not a good tactic...

**Comment by nalimilan** [comment]
I agree, let's deprecate `readtable` and offer a similar convenience function in CSV.jl which would allow loading data into a DataFrame as well as into any other structure.

**Comment by davidanthoff** [comment]
I would prefer that there is a ``readtable`` in the DataFrames package, I think for the occasional user it would be way too complicated that install a second package to read a CSV file into a DataFrame.

Maybe the DataFrames package could just REQUIRE the CSV package, and then the DataFrames ``readtable`` function just calls the CSV package stuff?

**Comment by nalimilan** [comment]
Why not return a `BigInt` instead of a string in case of overflow? That should use less memory, and still be usable as a number.

Regarding `readtable`, the problem with keeping it in DataFrames is that we're going to need a similar function e.g. for TypedTables, etc. I'd rather have a common interface . Though DataFrames could reexport that function.

**Comment by davidanthoff** [comment]
+1 to ``BigInt``

I don't really care where ``readtable`` would live, as long as 1) it is enough to ``Pkg.add("DataFrames"); using DataFrames`` to get it and 2) the DataFrames doc describes it etc. Essentially as long as a novice user who just wants to use DataFrames doesn't have to understand the interrelation of all these packages.

**Comment by johnmyleswhite** [comment]
One counter-argument to using `BigInt`: it's not available in several databases (in fact, the majority of Hadoop databases define `BigInt = Int64`), so we end up with somewhat weird semantics. I can see good arguments to ignore that, but it's worth noting.

**Comment by quinnj** [comment]
> Why not return a BigInt instead of a string in case of overflow? 

I think any kind of overflow-detection or "type-switching" is going to be a performance hit. You obviously have more flexibility in the "type detection" phase where you could indeed "detect" that a certain column would need an `Int128` or `BigInt` size integer type, but there would obviously be cases where type detection returned an `Int64`, yet further down in the column there was a value that overflowed.

What is super useful in CSV.jl is the ability to tell the parser what type a column should be, which allows the user full control over how things are brought in (e.g. manually specify BigInt if needed, or if you have really messy data, bring everything in as a string).

**Comment by nalimilan** [comment]
@quinnj So you mean we should just raise an error by default?

**Comment by davidanthoff** [comment]
I think a reader could show different behavior depending on whether the column type is specified or not. I think maybe the following would work:
- If no column types are specified, the reader should aggressively try to not lose any data. So for example, if the type detection phase came up with a type that can't hold data in a later row, either throw an error, or even better, switch the type at that point. I don't care that much whether it then switches to ``BigInt`` or ``String``, as long as it doesn't silently lose data (as it does right now). This scenario won't give you the best performance, but what the heck
- If one specifies a type for a column and the reader later detects a value that can't be represented by that type, I feel it should throw an error
- There could be a ``force`` mode or something where one specifies a type for the column, and switches of any overflow checking. This would be the fastest option, but one would have to be sure that all the values fit into the type one specifies, because otherwise one will end up with data corruption.

**Comment by quinnj** [comment]
Moved to https://github.com/JuliaData/CSV.jl/issues/100

**Comment by quinnj** [comment]
CSV.jl now throws an `OverflowError` in these cases, allowing the user to specify a wider integer column type when needed.
