### ISSUE TITLE
Support append in writetable 

### ISSUE THREAD

**Issue by guillaumeguy** [JuliaStats/DataFrames.jl#746]
It would be nice to have a flag for appending data (default to false) as part of the writetable arguments .

**Comment by guillaumeguy** [comment]
Sure. I will give it a try.

Here is what I suggest:
- If the file does not exist, do as if append==False
- if the file exists:
  - Check the number of columns, return a warning if it's different
  - Check the first row of the file, return a warning if they are different than our df's 

Question: Should we check the order of the columns and align it with the one in the file if different? Alternatively, we can just return a warning.

**Comment by garborg** [comment]
That sounds good, except instead of warning, throw errors (printing warnings is relatively uncommon in Julia).

And for your question, let's just throw an error instead of aligning -- that will be consistent with the `header=false` version, where it's only possible to check number of columns, not names, (and not types without reading the whole thing in, and still not foolproof then), so a consistent contract -- that the function expects consistent column order.

**Comment by garborg** [comment]
Closed by #755.
