### ISSUE TITLE
hcat inconsistency

### ISSUE THREAD

**Issue by fiatflux** [JuliaStats/DataFrames.jl#802]
I would expect
```
hcat([DataFrame(a=[1,2,3])]...)
```
to be have like
```
hcat([DataFrame(a=[1,2,3]), DataFrame(b=[4,5,6])]...)
```
by returning a DataFrame but instead it yields an array.

I recognize this looks like a strange example, but I have a situation wherein I need to hcat an arbitrary number of DataFrames and writing a special case for the situation of a single DataFrame seems ugly. (While we're at it, I reckon hcat() should return an empty DataFrame.)

**Comment by davidagold** [comment]
The functionality you're looking for seems more like an extension of `join`. Indeed, if you have an array of DataFrames `dfarray = [df_a, df_b, ... ]`, each with `N` observations, then I believe you could write something like
```julia
newdf = DataFrame()
for df in dfarray
    df[:ID] = 1:N
    newdf = join(newdf, df, on=:ID)
end
```
to achieve your desired result.

**Comment by fiatflux** [comment]
Sure that would work too, but honestly it tickles my aesthetic fancy less than explicitly dealing with hcat's present quirk. And either way, hcat ought to be consistent. Right now it returns either a DataFrame (similar to your solution) or an array of DataFrames -- depending on the number of arguments.

**Comment by davidagold** [comment]
That's fair. However, I don't think that `hcat()` should return an empty DataFrame. The following seems to work
```
julia> hcat(df1::DataFrame, df2, dfs...)=hcat(hcat(df1, df2), dfs...)
hcat (generic function with 21 methods)

julia> df1 = DataFrame(a=1:5)
5x1 DataFrame
| Row | a |
|-----|---|
| 1   | 1 |
| 2   | 2 |
| 3   | 3 |
| 4   | 4 |
| 5   | 5 |

julia> df2 = DataFrame(b=6:10)
5x1 DataFrame
| Row | b  |
|-----|----|
| 1   | 6  |
| 2   | 7  |
| 3   | 8  |
| 4   | 9  |
| 5   | 10 |

julia> df3 = DataFrame(c=11:15)
5x1 DataFrame
| Row | c  |
|-----|----|
| 1   | 11 |
| 2   | 12 |
| 3   | 13 |
| 4   | 14 |
| 5   | 15 |

julia> hcat(df1, df2, df3)
5x3 DataFrame
| Row | a | b  | c  |
|-----|---|----|----|
| 1   | 1 | 6  | 11 |
| 2   | 2 | 7  | 12 |
| 3   | 3 | 8  | 13 |
| 4   | 4 | 9  | 14 |
| 5   | 5 | 10 | 15 |
```
However, I have one large misgiving, namely that this implementation would potentially frustrate anybody who actually wants to create an array of DataFrame objects. Same goes for `vcat`. Maybe we should have something like `hjoin` and `vjoin` as the respective "concatenation" operators for DataFrame objects, though perhaps this usage is not entirely in keeping with a strict interpretation of "join".

**Comment by nalimilan** [comment]
This is related to more general debates about concatenation. Maybe people could write `Vector{DataFrame}[...]` to create a vector of DataFrames instead.

Anyway, `hcat(hcat(df1, df2), dfs...)` is not a great implementation since it's going to waste a lot of memory to store intermediate results of pair-by-pair concatenations.

**Comment by davidagold** [comment]
@nalimilan Which more general debates? Are you implying that the notion of `cat` applies more specifically to DataFrames than to Arrays? I'm not inclined one way or the other on this point, I'm just curious. I suppose if I were more familiar with the background debates I would understand. But either way, shouldn't we try to make it just as ergonomic to create a vector of DataFrames as to concatenate DataFrames into a single DataFrame?

W/r/t implementation, duly noted. What about creating a "target" DataFrame to mutate with the pair-by-pair concatenations and then return?

**Comment by nalimilan** [comment]
> @nalimilan Which more general debates? Are you implying that the notion of cat applies more specifically to DataFrames than to Arrays? I'm not inclined one way or the other on this point, I'm just curious. I suppose if I were more familiar with the background debates I would understand. But either way, shouldn't we try to make it just as ergonomic to create a vector of DataFrames as to concatenate DataFrames into a single DataFrame?

I see the present issue as similar to the question of what to do when calling `[[1, 2] [3, 4]]` or equivalently `hcat([1, 2], [3, 4])`, which currently returns an array. On the other hand, you can write `Vector[[1, 2], [3, 4]]` to get a vector of vectors if you really need it. I'd say the same should apply for data frames, not only for consistency, but also because creating a vector of data frames is less common than concatenating them.

A relevant issue is https://github.com/JuliaLang/julia/issues/7128 

> W/r/t implementation, duly noted. What about creating a "target" DataFrame to mutate with the pair-by-pair concatenations and then return?

Yeah, sounds like the strategy to follow.

**Comment by davidagold** [comment]
Ah, I see. So the stakes at hand are: does "concatenate", when applied to containers A, B of d-wise compatible shapes, mean "merge the values of A and B into a single container along dimension d" or does it mean "create an array whose objects are precisely A and B"?

I suppose the ambiguity arises because when A and B are not containers but rather objects, then the former interpretation applied to the singletons [A], [B] is equivalent to the latter interpretation applied to the objects A, B. Interesting. 

In any case, I will see about an implementation involving `hcat!`. @nalimilan do you have any thoughts about whether `hcat()` should return an empty Array or DataFrame? I suppose we could do `hcat()` returns empty DataFrame and `vcat()` returns empty Array?

**Comment by garborg** [comment]
`Base.hcat()` belongs to broader Julia and switching it to return a `DataFrame` when this package is loaded would be break code unrelated to DataFrames, so that's a no-go:
```julia
julia> x = hcat()
0-element Array{Any,1}
julia> using DataFrames
julia> y = hcat()
0-element Array{Any,1}
```

Agreed that `hcat(::DataFrame)` should return a `DataFrame` if `hcat` is what is used for concatenating an arbitrary number of DataFrames, but as @nalimilan pointed out, that's not an ideal pattern.

You could try `DataFrames.hcat!`, which does what @nalimilan recommended. It's used broadly internally, but unexported as we're being conservative about expanding the API until we get through some more design experimentation. E.g.:

```julia
julia> using DataFrames
julia> DataFrames.hcat!(DataFrame(), DataFrame[]...)
0x0 DataFrames.DataFrame
```

OR

```julia
julia> using DataFrames
julia> using DataFrames: hcat!
julia> hcat!(DataFrame(), DataFrame[]...)
0x0 DataFrames.DataFrame
```

I've added a commit locally to support the 1-argument version of `hcat!`, and I'll push it up later this morning.
