### ISSUE TITLE
Format numbers

### ISSUE THREAD

**Issue by cwiese** [JuliaStats/DataFrames.jl#844]
Is there an easy way to format Float to #,###,### with no scientific notation?

**Comment by kmsquire** [comment]
Hi @cwiese, generally, this kind of question is best asked on the julia-users mailing list first, and if the answer is negative, perhaps opening a relevant issue.

A partial answer is that it is possible to print numbers in that format with `Formatting.jl`, but since you posted your question in `DataFrames.jl`, I assume you want to do that in a `DataFrame`, and I don't know if that's possible.

So... while someone else might answer here, your best bet would be to ask on julia-users.  Cheers!
