### ISSUE TITLE
'Encountered flag 1539 corresponding to type Closure'  error after reading a rdata file

### ISSUE THREAD

**Issue by joermungandr** [JuliaStats/DataFrames.jl#849]
Hi! I tried to read a rdata file from R-Studio using ```read_rda("/test.RData")``` which caused this error message:

```
ERROR: Encountered flag 1539 corresponding to type Closure
 in error at error.jl:21
 in readitem at /Users/icarus/.julia/v0.3/DataFrames/src/RDA.jl:401
 in readnamedobjects at /Users/icarus/.julia/v0.3/DataFrames/src/RDA.jl:322
 in read_rda at /Users/icarus/.julia/v0.3/DataFrames/src/RDA.jl:413
 in anonymous at /Users/icarus/.julia/v0.3/DataFrames/src/RDA.jl:418
 in gzopen at /Users/icarus/.julia/v0.3/GZip/src/GZip.jl:266
 in read_rda at /Users/icarus/.julia/v0.3/DataFrames/src/RDA.jl:418
```
Is this a known error? I use Julia v0.3.10.

**Comment by alyst** [comment]
It's an intended behaviour: closures are among those things that are not supported by ```read_rda()```. For every other non-supported SEXP type you should get the same error.
It's not likely that R closures would have any use in Julia session, but the problem is that you cannot just skip them: there's no simple way to know how many bytes one should skip, also it  could contain elements that are referenced later in the stream  -- and if that's ignored, the whole indexing of references would be broken.
So reading an arbitrary RData file requires proper parsing of every SEXP type. Making it stable is a considerable effort. Meanwhile, the solution would be either to read RData files that contain only supported elements or use the packages for calling R from Julia session, e.g. [RCall](http://github.com/JuliaStats/RCalll.jl).
I've done some work to support the other SEXP types. There's [RData](http://github.com/alyst/RData.jl) package, but it's very experimental and would probably work only in Julia 0.4.
