### ISSUE TITLE
Undocumented use of ^ in formulae

### ISSUE THREAD

**Issue by pkofod** [JuliaStats/DataFrames.jl#861]
What is the syntax for using `^` in a formula? I can get all the other specials to work, but I can't seem to make `^` work. Can anyone elaborate on the correct syntax?

**Comment by kleinschmidt** [comment]
I think it's not actually used for anything anymore. Formulas have changed quite a bit since they were first implemented. At one point there was a way to quote expressions that would lazily evaluated against a data frame during model matrix construction, but that feature was removed in general from DataFrames itself for performance reasons.

**Comment by pkofod** [comment]
That seems to answer my question. Thanks.

**Comment by kleinschmidt** [comment]
You're quite welcome!
