### ISSUE TITLE
writetable escapes

### ISSUE THREAD

**Issue by LouisMagarshack** [JuliaStats/DataFrames.jl#924]
Hi all,

I'm wondering why in DataFrames.jl/src/abstractdataframe/io.jl `printtable` is escaping `"\"'"` regardless of the quotemark.

I'm referring to the following call `escapedprint(io, df[i, j], "\"'")` which I would make more sense as `escapedprint(io, df[i, j], "$quotemark")`.

I figured I would ask since I'm not a CSV expert!

Cheers,
Louis

**Comment by nalimilan** [comment]
I can imagine only one justification, which would be that `printtable` is also used to print a data frame to the REPL, where `"` and `'` will always be interpreted by Julia as quotes. But I don't think that's the reason since that output isn't supposed to be interpreted again as valid Julia code.

So I think this is an oversight. Indeed in means that any output containing a custom quotemark in one of its fields would be broken, which is clearly a bug. You can wait for more input from others, but I would think it would be great if you could make a pull request to this this. Ideally, it would also add a small test to check that this bug does not reappear in the future. Thanks!

**Comment by LouisMagarshack** [comment]
Thanks for the reply!
I'll make a pull request later today

**Comment by LouisMagarshack** [comment]
I opened #925

**Comment by quinnj** [comment]
`readtable`/`printtable` are now deprecated in favor of the CSV.jl and TextParse.jl packages.
