### ISSUE TITLE
Cannot use NullableArray in a data frame

### ISSUE THREAD

**Issue by nalimilan** [JuliaStats/DataFrames.jl#933]
I see this with latest master of DataFrames and NullableArrays:
```julia
julia> DataFrame(y=NullableArray([1,2]))
ERROR: MethodError: `upgrade_vector` has no method matching upgrade_vector(::NullableArrays.NullableArray{Int64,1})
 in setindex! at /home/milan/.julia/DataFrames/src/dataframe/dataframe.jl:368
 in DataFrame at /home/milan/.julia/DataFrames/src/dataframe/dataframe.jl:104
```

I suspect I'm missing something, since people seem to be doing this all the time (e.g. https://github.com/JuliaStats/DataFramesMeta.jl/issues/42).

**Comment by amellnik** [comment]
To anyone else who sees a similar error and ends up here: DataFrames with NullableArray columns need to be constructed all at once, and can't currently have additional columns added.  This means that while you can do things like:

```julia
DataFrame(Any[NullableArray([1,2])], Symbol[:y])
```

to construct a DataFrame, you can't subsequently add more columns with something like

```julia
df[:col] = NullableArray([1,2])
```

    LoadError: MethodError: `upgrade_vector` has no method matching upgrade_vector(::NullableArrays.NullableArray{Int64,1})
    while loading In[9], in expression starting on line 2

     in setindex! at C:\Users\amellnik\.julia\v0.4\DataFrames\src\dataframe\dataframe.jl:368

If you have a DataFrame with NullableArrays for columns and you need to add columns or otherwise convert it to a vanilla DataFrame (with DataArray columns) you can use something like

```julia
function NullableDFtoDF!(ndf)
    for c in names(ndf)
        ndf[c] = DataArray(ndf[c].values, ndf[c].isnull)
    end
end

function DFtoNullableDF(df)
    DataFrame(Any[NullableArray(df[c].data,
        Array{Bool}(df[c].na)) for c in names(df)], names(df))
end
```

**Comment by nalimilan** [comment]
See https://github.com/JuliaStats/DataFrames.jl/pull/1008.
